### ISSUE TITLE
Redis: Automatically tune based on available memory

### ISSUE THREAD

**Issue by dokterbob** [ipfs-search/ipfs-search-deployment#25]

**Comment by spookyrecharge** [comment]
https://github.com/ipfs-search/ipfs-search-deployment/commit/9645c117c31c50feb1388a0e7ea54d068f81c786

Now we can pass var which is take % for a redis from total host available memory. By default, it's 80%.

@dokterbob please review and close issue if everything is ok

**Comment by dokterbob** [comment]
@spookyrecharge Great start. But, as mentioned, there will be multiple nodes running.

Did you do any stress testing? In production tests I found it necessary to restrict max mem to ~2gb per node (so ~4gb total). Using ~3gb per node (so 6 of 8 available gb) led to Linux' OOM killer shooting nodes down and general instability.

**Comment by dokterbob** [comment]
Actually, after deploying from `recent-issues`, the nodes are using only 1gb of memory.
